// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc2/command/SubsystemBase.h"
#include "rev/CANSparkMax.h"
#include "hwcfg.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class Feeder: public frc2::SubsystemBase {
private:
	rev::CANSparkMax m_storage{CANIDs::kFeederMotorID, rev::CANSparkMax::MotorType::kBrushless};
	rev::CANPIDController m_pidStorageController{m_storage.GetPIDController()};
	rev::CANEncoder m_storageEncoder{m_storage.GetEncoder()};
	const double kRotateRPM;
	const double kP;
	const double kFF;
	const double kMaxAccel;

public:
	Feeder();
	void Periodic() override;
	void RotateCW(void);
	void RotateCW(double rpm);
	void RotateCCW(void);
	void RotateCCW(double rpm);
	void FeedStop(void);
	void Agitate(void);

};

