// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc2/command/SubsystemBase.h"
#include "hwcfg.h"
#include "frc/DoubleSolenoid.h"
#include "ctre/Phoenix.h"

#define DEFAULT_INTAKE_VOLTS 1.0

/**
 *
 *
 * @author ExampleAuthor
 */
class Intake: public frc2::SubsystemBase {
private:
	frc::DoubleSolenoid m_intakeSol{PCMIDs::kIntakeSolFwd, PCMIDs::kIntakeSolRev};
	WPI_VictorSPX m_intakeMotor{CANIDs::kIntakeMotorID};
public:
Intake();
	void Periodic() override;
	void IntakeUp(){m_intakeSol.Set(frc::DoubleSolenoid::kForward);}
	void IntakeDown(){m_intakeSol.Set(frc::DoubleSolenoid::kReverse);}
	void IntakeOn(double speed = DEFAULT_INTAKE_VOLTS){m_intakeMotor.Set(speed);}
	void IntakeOff(void){m_intakeMotor.Set(0.0);}
	void IntakeReverse(double speed = DEFAULT_INTAKE_VOLTS) {m_intakeMotor.Set(-speed);}
};

