// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/TimedRobot.h"
#include "frc2/command/Command.h"
#include "frc/livewindow/LiveWindow.h"
#include "frc/smartdashboard/SendableChooser.h"
#include "frc/smartdashboard/SmartDashboard.h"
#include "frc/DigitalOutput.h"

#include "Commands/AutonomousCommand.h"
#include "Subsystems/Climber.h"
#include "Subsystems/DriveTrain.h"
#include "Subsystems/Feeder.h"
#include "Subsystems/Intake.h"
#include "Subsystems/Loader.h"
#include "Subsystems/Shooter.h"
#include "Subsystems/Vision.h"

#include "RobotContainer.h"
#include "hwcfg.h"

#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc2::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	void RobotInit() override;
	void RobotPeriodic() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;
	void sendLEDCode(int code);

private:
	frc2::Command* m_autonomousCommand = nullptr;
	RobotContainer m_container;

	// LED Strip DIOs
	std::shared_ptr<frc::DigitalOutput> dataOutPin1;
  	std::shared_ptr<frc::DigitalOutput> dataOutPin2;
  	std::shared_ptr<frc::DigitalOutput> dataOutPin3;
};
