// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Climber.h"
#include <frc/smartdashboard/SmartDashboard.h>

Climber::Climber() {
}

void Climber::Periodic() {
    // Put code here to be run every loop
    frc::SmartDashboard::PutBoolean("Climber Released", IsInterlockReleased());
}

void Climber::WinchExtend(double speed) {
    if (m_InterlockRelease) {
        m_climberMotor.Set(-speed);
    }
    else {
        m_climberMotor.StopMotor();
    }
}

void Climber::WinchRetract(double speed) {
    if (m_InterlockRelease) {
        m_climberMotor.Set(speed);
    }
    else {
        m_climberMotor.StopMotor();
    }
}
